<?php

namespace Database\Seeders;

use App\Models\marks;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MarksSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $makes = [
            ['id' => 1,'name' => 'ACURA','vehicle_types_id' => 1],
            ['id' => 2,'name' => 'ALFA ROMEO','vehicle_types_id' => 1],
            ['id' => 121,'name' => 'AM GENERAL','vehicle_types_id' => 1],
            ['id' => 3,'name' => 'AMERICAN IRONHORSE','vehicle_types_id' => 1],
            ['id' => 134,'name' => 'AMERICAN LAFRANCE','vehicle_types_id' => 1],
            ['id' => 5,'name' => 'APRILIA','vehicle_types_id' => 1],
            ['id' => 6,'name' => 'ARCTIC CAT','vehicle_types_id' => 1],
            ['id' => 126,'name' => 'ARGO','vehicle_types_id' => 1],
            ['id' => 4,'name' => 'ASTON MARTIN','vehicle_types_id' => 1],
            ['id' => 111,'name' => 'ATK','vehicle_types_id' => 1],
            ['id' => 7,'name' => 'AUDI','vehicle_types_id' => 1],
            ['id' => 8,'name' => 'AUTOCAR LLC.','vehicle_types_id' => 1],
            ['id' => 9,'name' => 'AVANTI','vehicle_types_id' => 1],
            ['id' => 10,'name' => 'BENTLEY','vehicle_types_id' => 1],
            ['id' => 138,'name' => 'BERTONE','vehicle_types_id' => 1],
            ['id' => 135,'name' => 'BETA','vehicle_types_id' => 1],
            ['id' => 13,'name' => 'BIG DOG','vehicle_types_id' => 1],
            ['id' => 122,'name' => 'BIMOTA','vehicle_types_id' => 1],
            ['id' => 11,'name' => 'BLUE BIRD','vehicle_types_id' => 1],
            ['id' => 12,'name' => 'BMW','vehicle_types_id' => 1],
            ['id' => 127,'name' => 'BOBCAT','vehicle_types_id' => 1],
            ['id' => 14,'name' => 'BOMBARDIER','vehicle_types_id' => 1],
            ['id' => 15,'name' => 'BUELL','vehicle_types_id' => 1],
            ['id' => 133,'name' => 'BUGATTI','vehicle_types_id' => 1],
            ['id' => 16,'name' => 'BUICK','vehicle_types_id' => 1],
            ['id' => 18,'name' => 'CADILLAC','vehicle_types_id' => 1],
            ['id' => 128,'name' => 'CAN-AM','vehicle_types_id' => 1],
            ['id' => 17,'name' => 'CANNONDALE','vehicle_types_id' => 1],
            ['id' => 117,'name' => 'CHANCE COACH TRANSIT BUS','vehicle_types_id' => 1],
            ['id' => 19,'name' => 'CHEVROLET','vehicle_types_id' => 1],
            ['id' => 20,'name' => 'CHRYSLER','vehicle_types_id' => 1],
            ['id' => 21,'name' => 'COBRA','vehicle_types_id' => 1],
            ['id' => 143,'name' => 'CODA','vehicle_types_id' => 1],
            ['id' => 22,'name' => 'COUNTRY COACH MOTORHOME','vehicle_types_id' => 1],
            ['id' => 136,'name' => 'CRANE CARRIER','vehicle_types_id' => 1],
            ['id' => 129,'name' => 'CUB CADET','vehicle_types_id' => 1],
            ['id' => 118,'name' => 'DAEWOO','vehicle_types_id' => 1],
            ['id' => 24,'name' => 'DODGE','vehicle_types_id' => 1],
            ['id' => 23,'name' => 'DUCATI','vehicle_types_id' => 1],
            ['id' => 27,'name' => 'E-TON','vehicle_types_id' => 1],
            ['id' => 25,'name' => 'EL DORADO','vehicle_types_id' => 1],
            ['id' => 26,'name' => 'FERRARI','vehicle_types_id' => 1],
            ['id' => 28,'name' => 'FIAT','vehicle_types_id' => 1],
            ['id' => 144,'name' => 'FISKER','vehicle_types_id' => 1],
            ['id' => 29,'name' => 'FORD','vehicle_types_id' => 1],
            ['id' => 30,'name' => 'FREIGHTLINER','vehicle_types_id' => 1],
            ['id' => 31,'name' => 'GAS GAS','vehicle_types_id' => 1],
            ['id' => 33,'name' => 'GILLIG','vehicle_types_id' => 1],
            ['id' => 32,'name' => 'GMC','vehicle_types_id' => 1],
            ['id' => 34,'name' => 'HARLEY DAVIDSON','vehicle_types_id' => 1],
            ['id' => 35,'name' => 'HINO','vehicle_types_id' => 1],
            ['id' => 38,'name' => 'HM','vehicle_types_id' => 1],
            ['id' => 36,'name' => 'HONDA','vehicle_types_id' => 1],
            ['id' => 37,'name' => 'HUMMER','vehicle_types_id' => 1],
            ['id' => 39,'name' => 'HUSABERG','vehicle_types_id' => 1],
            ['id' => 40,'name' => 'HUSQVARNA','vehicle_types_id' => 1],
            ['id' => 115,'name' => 'HYOSUNG','vehicle_types_id' => 1],
            ['id' => 41,'name' => 'HYUNDAI','vehicle_types_id' => 1],
            ['id' => 139,'name' => 'IC CORPORATION','vehicle_types_id' => 1],
            ['id' => 112,'name' => 'INDIAN','vehicle_types_id' => 1],
            ['id' => 42,'name' => 'INFINITI','vehicle_types_id' => 1],
            ['id' => 43,'name' => 'INTERNATIONAL','vehicle_types_id' => 1],
            ['id' => 44,'name' => 'ISUZU','vehicle_types_id' => 1],
            ['id' => 45,'name' => 'JAGUAR','vehicle_types_id' => 1],
            ['id' => 46,'name' => 'JEEP','vehicle_types_id' => 1],
            ['id' => 47,'name' => 'JOHN DEERE','vehicle_types_id' => 1],
            ['id' => 50,'name' => 'KASEA','vehicle_types_id' => 1],
            ['id' => 48,'name' => 'KAWASAKI','vehicle_types_id' => 1],
            ['id' => 49,'name' => 'KENWORTH','vehicle_types_id' => 1],
            ['id' => 52,'name' => 'KIA','vehicle_types_id' => 1],
            ['id' => 51,'name' => 'KTM','vehicle_types_id' => 1],
            ['id' => 53,'name' => 'KUBOTA','vehicle_types_id' => 1],
            ['id' => 54,'name' => 'KYMCO','vehicle_types_id' => 1],
            ['id' => 123,'name' => 'LAFORZA','vehicle_types_id' => 1],
            ['id' => 55,'name' => 'LAMBORGHINI','vehicle_types_id' => 1],
            ['id' => 56,'name' => 'LAND ROVER','vehicle_types_id' => 1],
            ['id' => 113,'name' => 'LEM','vehicle_types_id' => 1],
            ['id' => 59,'name' => 'LEXUS','vehicle_types_id' => 1],
            ['id' => 57,'name' => 'LINCOLN','vehicle_types_id' => 1],
            ['id' => 58,'name' => 'LOTUS','vehicle_types_id' => 1],
            ['id' => 60,'name' => 'MACK','vehicle_types_id' => 1],
            ['id' => 61,'name' => 'MASERATI','vehicle_types_id' => 1],
            ['id' => 62,'name' => 'MAYBACH','vehicle_types_id' => 1],
            ['id' => 64,'name' => 'MAZDA','vehicle_types_id' => 1],
            ['id' => 141,'name' => 'MCLAREN','vehicle_types_id' => 1],
            ['id' => 63,'name' => 'MERCEDES-BENZ','vehicle_types_id' => 1],
            ['id' => 65,'name' => 'MERCURY','vehicle_types_id' => 1],
            ['id' => 66,'name' => 'MINI','vehicle_types_id' => 1],
            ['id' => 68,'name' => 'MITSUBISHI','vehicle_types_id' => 1],
            ['id' => 67,'name' => 'MITSUBISHI FUSO','vehicle_types_id' => 1],
            ['id' => 69,'name' => 'MORGAN','vehicle_types_id' => 1],
            ['id' => 71,'name' => 'MOTO GUZZI','vehicle_types_id' => 1],
            ['id' => 70,'name' => 'MOTOR COACH INDUSTRIES','vehicle_types_id' => 1],
            ['id' => 73,'name' => 'MV AGUSTA','vehicle_types_id' => 1],
            ['id' => 140,'name' => 'NASH','vehicle_types_id' => 1],
            ['id' => 72,'name' => 'NEW FLYER','vehicle_types_id' => 1],
            ['id' => 74,'name' => 'NISSAN','vehicle_types_id' => 1],
            ['id' => 75,'name' => 'NOVA BUS CORPORATION','vehicle_types_id' => 1],
            ['id' => 76,'name' => 'OLDSMOBILE','vehicle_types_id' => 1],
            ['id' => 77,'name' => 'ORION BUS','vehicle_types_id' => 1],
            ['id' => 78,'name' => 'OSHKOSH MOTOR TRUCK CO.','vehicle_types_id' => 1],
            ['id' => 119,'name' => 'OTTAWA','vehicle_types_id' => 1],
            ['id' => 81,'name' => 'PANOZ','vehicle_types_id' => 1],
            ['id' => 79,'name' => 'PETERBILT','vehicle_types_id' => 1],
            ['id' => 80,'name' => 'PEUGEOT','vehicle_types_id' => 1],
            ['id' => 116,'name' => 'PIAGGIO','vehicle_types_id' => 1],
            ['id' => 130,'name' => 'PIERCE MFG. INC.','vehicle_types_id' => 1],
            ['id' => 124,'name' => 'PLYMOUTH','vehicle_types_id' => 1],
            ['id' => 82,'name' => 'POLARIS','vehicle_types_id' => 1],
            ['id' => 83,'name' => 'PONTIAC','vehicle_types_id' => 1],
            ['id' => 85,'name' => 'PORSCHE','vehicle_types_id' => 1],
            ['id' => 120,'name' => 'QVALE','vehicle_types_id' => 1],
            ['id' => 131,'name' => 'RAM','vehicle_types_id' => 1],
            ['id' => 84,'name' => 'RENAULT','vehicle_types_id' => 1],
            ['id' => 88,'name' => 'ROLLS ROYCE','vehicle_types_id' => 1],
            ['id' => 114,'name' => 'ROVER','vehicle_types_id' => 1],
            ['id' => 86,'name' => 'SAAB','vehicle_types_id' => 1],
            ['id' => 87,'name' => 'SALEEN','vehicle_types_id' => 1],
            ['id' => 89,'name' => 'SATURN','vehicle_types_id' => 1],
            ['id' => 93,'name' => 'SCION','vehicle_types_id' => 1],
            ['id' => 90,'name' => 'SEA-DOO','vehicle_types_id' => 1],
            ['id' => 91,'name' => 'SEAT','vehicle_types_id' => 1],
            ['id' => 92,'name' => 'SKI-DOO','vehicle_types_id' => 1],
            ['id' => 94,'name' => 'SMART','vehicle_types_id' => 1],
            ['id' => 142,'name' => 'SRT','vehicle_types_id' => 1],
            ['id' => 96,'name' => 'STERLING','vehicle_types_id' => 1],
            ['id' => 95,'name' => 'STERLING TRUCK','vehicle_types_id' => 1],
            ['id' => 97,'name' => 'SUBARU','vehicle_types_id' => 1],
            ['id' => 99,'name' => 'SUZUKI','vehicle_types_id' => 1],
            ['id' => 132,'name' => 'TESLA','vehicle_types_id' => 1],
            ['id' => 98,'name' => 'TM','vehicle_types_id' => 1],
            ['id' => 102,'name' => 'TOYOTA','vehicle_types_id' => 1],
            ['id' => 100,'name' => 'TRIUMPH','vehicle_types_id' => 1],
            ['id' => 101,'name' => 'UD','vehicle_types_id' => 1],
            ['id' => 103,'name' => 'VENTO','vehicle_types_id' => 1],
            ['id' => 104,'name' => 'VESPA','vehicle_types_id' => 1],
            ['id' => 105,'name' => 'VICTORY','vehicle_types_id' => 1],
            ['id' => 106,'name' => 'VOLKSWAGEN','vehicle_types_id' => 1],
            ['id' => 108,'name' => 'VOLVO','vehicle_types_id' => 1],
            ['id' => 137,'name' => 'VPG','vehicle_types_id' => 1],
            ['id' => 107,'name' => 'WESTERN RV','vehicle_types_id' => 1],
            ['id' => 125,'name' => 'WESTERN STAR','vehicle_types_id' => 1],
            ['id' => 109,'name' => 'WORKHORSE','vehicle_types_id' => 1],
            ['id' => 110,'name' => 'YAMAHA','vehicle_types_id' => 1]
          ];

        // Insertar datos en la tabla tipo_vehiculos
        foreach ($makes as $make) {
            $Marcasx = marks::create($make);
            echo $Marcasx . "Marca:";
        }
    }
}
